In [2]:
import pandas as pd

In [128]:
df = pd.read_csv(f"/Users/liuda/Local/data/trading/data/KOL/YTB_KOL.csv")
SPY_trading_date = pd.read_csv(f'/Users/liuda/Local/data/trading/data/stocks/ticker/history/SPY.csv')

In [ ]:
SPY_trading_date

In [129]:
df = df.drop(columns=['trading_date'])

In [131]:
df['publish_date'] = pd.to_datetime(df['publish_date'], format='%Y-%m-%d', errors='coerce')
SPY_trading_date['Date'] = pd.to_datetime(SPY_trading_date['Date'], format='%Y-%m-%d', errors='coerce')

In [150]:
df1 = pd.merge(df, SPY_trading_date, left_on='publish_date', right_on='Date', how='outer').reset_index(drop=True)

In [147]:
df1['trading_date'] = df1['Date'].ffill()  # 线上使用

In [148]:
# df[['publish_date']]
# SPY_trading_date[['Date']]
df1 = df1.dropna(subset=['publish_date'])

In [149]:
df1[['publish_date', 'Date', 'trading_date']]

     publish_date       Date trading_date
3763   2025-03-01        NaT   2025-02-28
3764   2025-03-01        NaT   2025-02-28
3765   2025-03-01        NaT   2025-02-28
3766   2025-03-01        NaT   2025-02-28
3767   2025-03-01        NaT   2025-02-28
3768   2025-03-01        NaT   2025-02-28
3769   2025-03-01        NaT   2025-02-28
3770   2025-03-01        NaT   2025-02-28
3771   2025-03-02        NaT   2025-02-28
3772   2025-03-02        NaT   2025-02-28
3773   2025-03-02        NaT   2025-02-28
3774   2025-03-02        NaT   2025-02-28
3775   2025-03-02        NaT   2025-02-28
3776   2025-03-02        NaT   2025-02-28
3777   2025-03-02        NaT   2025-02-28
3779   2025-03-04 2025-03-04   2025-03-04
3780   2025-03-04 2025-03-04   2025-03-04
3781   2025-03-04 2025-03-04   2025-03-04
3782   2025-03-04 2025-03-04   2025-03-04
3783   2025-03-04 2025-03-04   2025-03-04
3784   2025-03-04 2025-03-04   2025-03-04
3785   2025-03-04 2025-03-04   2025-03-04
3786   2025-03-04 2025-03-04   2025-03-04
3787   2025-03-04 2025-03-04   2025-03-04
3788   2025-03-04 2025-03-04   2025-03-04
3789   2025-03-04 2025-03-04   2025-03-04
3790   2025-03-04 2025-03-04   2025-03-04
3791   2025-03-04 2025-03-04   2025-03-04
3792   2025-03-04 2025-03-04   2025-03-04
3793   2025-03-04 2025-03-04   2025-03-04
3794   2025-03-04 2025-03-04   2025-03-04
3795   2025-03-04 2025-03-04   2025-03-04
3796   2025-03-05 2025-03-05   2025-03-05
3797   2025-03-05 2025-03-05   2025-03-05
3798   2025-03-05 2025-03-05   2025-03-05
3799   2025-03-05 2025-03-05   2025-03-05
3800   2025-03-05 2025-03-05   2025-03-05
3801   2025-03-05 2025-03-05   2025-03-05
3802   2025-03-05 2025-03-05   2025-03-05
3803   2025-03-05 2025-03-05   2025-03-05
3804   2025-03-05 2025-03-05   2025-03-05
3805   2025-03-05 2025-03-05   2025-03-05
3806   2025-03-05 2025-03-05   2025-03-05
3807   2025-03-05 2025-03-05   2025-03-05
3808   2025-03-05 2025-03-05   2025-03-05
3809   2025-03-05 2025-03-05   2025-03-05
3810   2025-03-05 2025-03-05   2025-03-05
3811   2025-03-05 2025-03-05   2025-03-05
3812   2025-03-05 2025-03-05   2025-03-05
3813   2025-03-05 2025-03-05   2025-03-05
3814   2025-03-05 2025-03-05   2025-03-05
3815   2025-03-05 2025-03-05   2025-03-05
3816   2025-03-05 2025-03-05   2025-03-05
3817   2025-03-06 2025-03-06   2025-03-06
3818   2025-03-06 2025-03-06   2025-03-06
3819   2025-03-06 2025-03-06   2025-03-06
3820   2025-03-06 2025-03-06   2025-03-06
3821   2025-03-06 2025-03-06   2025-03-06
3822   2025-03-06 2025-03-06   2025-03-06
3823   2025-03-06 2025-03-06   2025-03-06
3824   2025-03-06 2025-03-06   2025-03-06
3825   2025-03-06 2025-03-06   2025-03-06
3826   2025-03-07 2025-03-07   2025-03-07
3827   2025-03-07 2025-03-07   2025-03-07
3828   2025-03-07 2025-03-07   2025-03-07
3829   2025-03-07 2025-03-07   2025-03-07
3830   2025-03-07 2025-03-07   2025-03-07
3831   2025-03-07 2025-03-07   2025-03-07
3832   2025-03-07 2025-03-07   2025-03-07
3833   2025-03-07 2025-03-07   2025-03-07
3834   2025-03-07 2025-03-07   2025-03-07
3835   2025-03-07 2025-03-07   2025-03-07
3836   2025-03-07 2025-03-07   2025-03-07
3837   2025-03-08        NaT   2025-03-07
3838   2025-03-08        NaT   2025-03-07
3839   2025-03-08        NaT   2025-03-07
3840   2025-03-08        NaT   2025-03-07
3841   2025-03-08        NaT   2025-03-07
3842   2025-03-08        NaT   2025-03-07
3843   2025-03-08        NaT   2025-03-07
3845   2025-03-11 2025-03-11   2025-03-11
3846   2025-03-11 2025-03-11   2025-03-11
3847   2025-03-11 2025-03-11   2025-03-11
3848   2025-03-11 2025-03-11   2025-03-11
3849   2025-03-11 2025-03-11   2025-03-11
3850   2025-03-11 2025-03-11   2025-03-11
3851   2025-03-11 2025-03-11   2025-03-11
3852   2025-03-11 2025-03-11   2025-03-11
3853   2025-03-11 2025-03-11   2025-03-11
3854   2025-03-11 2025-03-11   2025-03-11
3855   2025-03-11 2025-03-11   2025-03-11
3856   2025-03-11 2025-03-11   2025-03-11
3857   2025-03-11 2025-03-11   2025-03-11
3858   2025-03-11 2025-03-11   2025-03-11
3859   2025-03-11 2025-03-11   2025-03-11
3860   2025-03-11 2025-03-11   2025-03-11
3861   2025-03-11 2025-03-11   2025-03-11
3862   2025-03-11 2025-03-11   2025-03-11
3863   2025-03-11 2025-03-11   2025-03-11
3864   2025-03-11 2025-03-11   2025-03-11
3865   2025-03-11 2025-03-11   2025-03-11
3866   2025-03-11 2025-03-11   2025-03-11
3867   2025-03-11 2025-03-11   2025-03-11
3868   2025-03-12 2025-03-12   2025-03-12
3869   2025-03-12 2025-03-12   2025-03-12
3870   2025-03-13        NaT   2025-03-12
3871   2025-03-13        NaT   2025-03-12
3872   2025-03-13        NaT   2025-03-12
3873   2025-03-13        NaT   2025-03-12
3874   2025-03-13        NaT   2025-03-12
3875   2025-03-13        NaT   2025-03-12