In [1]:
import sys
sys.path.append('/Users/liuda/Library/CloudStorage/Dropbox/shareit/code/trading/algotrading')

In [2]:
from backend.hedge import init_hedge_parsed_data

In [4]:
from backend.logger import get_logger

logger = get_logger("test", "test.log")

In [9]:
hedge_data_input = '/Users/liuda/Local/data/trading/data/hedgeparsing/*_form13f/alltrading/part*'

In [12]:
from backend.utils.pandas_utils import PandasUtils
from backend.strategy_v2.hedge import redefine_level
import pandas as pd

hedge_data = PandasUtils().read_multiple_files(hedge_data_input, logger, sep='\t', index_col=False)
from backend.utils import ticker_utils
ticker_mapping = ticker_utils.load_ticker_mapping('/Users/liuda/Local/data/trading/data/cnsfails/merge/cnsfails.csv')
hedge_data = pd.merge(hedge_data, ticker_mapping, on='CUSIP', how='left')
hedge_data = hedge_data.rename(columns={'SYMBOL': 'TICKER'})
hedge_data = redefine_level(hedge_data)

2025-03-19 14:57:16 - INFO - read_multiple_files from /Users/liuda/Local/data/trading/data/hedgeparsing/*_form13f/alltrading/part*
2025-03-19 14:57:16 - INFO - 47 files in file_paths: /Users/liuda/Local/data/trading/data/hedgeparsing/*_form13f/alltrading/part*

In [13]:
hedge_data

,CUSIP,TICKER,MANAGER_LEVEL,YEAR,QUARTER,DATA_YEAR,DATA_QURT,INC_VALUE,DRC_VALUE,INC_COUNT,DRC_COUNT,TOTAL_VALUE,TOTAL_PREVALUE,TOTAL_SSHPRNAMT,TOTAL_PRESSHPRNAMT,HIS_AVG_DRC_VAL,HIS_DRC_COUNT,HIS_AVG_INC_VAL,HIS_INC_COUNT,TOP_HOLD_COUNT
0,000304105,AACAY,0.0,2013,3,2013,2,1135000,0,2,0,1135000,0,20092,0,0.0,0.0,0.0,0.0,0
1,000304105,AACAY,0.0,2013,4,2013,3,0,-207000,0,2,928000,1135000,20425,20092,0.0,0.0,0.0,0.0,0
2,000304105,AACAY,0.0,2014,1,2013,4,102000,0,1,0,1026000,924000,21133,20326,-207000.0,1.0,1135000.0,1.0,0
3,000304105,AACAY,0.0,2014,2,2014,1,158000,0,1,0,1184000,1026000,22868,21133,-207000.0,1.0,1135000.0,1.0,0
4,000304105,AACAY,0.0,2014,3,2014,2,281000,0,1,0,1465000,1184000,22502,22868,-207000.0,1.0,1135000.0,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1424045,y95308105,WVE,5.0,2024,1,2023,4,2171126,-62486,6,1,6771142,4662502,1340822,810871,-15295058.0,5.0,117023112.0,7.0,0
1424046,y95308105,WVE,5.0,2024,2,2024,1,1717692,-721085,7,1,7656346,6659739,1240901,1318762,-15295058.0,5.0,117023112.0,7.0,0
1424047,y95308105,WVE,5.0,2024,3,2024,2,28351,-2537275,2,6,5147422,7656346,1031549,1240901,-15295058.0,5.0,117023112.0,7.0,0
1424048,y95308105,WVE,5.0,2024,4,2024,3,4277984,-7375,6,1,9288321,5017712,1132722,1005555,-15295058.0,5.0,117023112.0,7.0,0
1424049,y95308105,WVE,5.0,2025,1,2024,4,3151014,-731777,7,1,5911872,3492635,477921,425931,-16968279.0,6.0,125022265.0,8.0,0

In [22]:
hedge_data[(hedge_data['TICKER'] == 'TSM') & (hedge_data['YEAR'] == 2022) & (hedge_data['MANAGER_LEVEL'].isin([0, 1]))]

,CUSIP,TICKER,MANAGER_LEVEL,YEAR,QUARTER,DATA_YEAR,DATA_QURT,INC_VALUE,DRC_VALUE,INC_COUNT,DRC_COUNT,TOTAL_VALUE,TOTAL_PREVALUE,TOTAL_SSHPRNAMT,TOTAL_PRESSHPRNAMT,HIS_AVG_DRC_VAL,HIS_DRC_COUNT,HIS_AVG_INC_VAL,HIS_INC_COUNT,TOP_HOLD_COUNT
1171861,874039100,TSM,0.0,2022,1,2021,4,797678600,-81265000,126,22,2861789600,2145376000,20740967,19200403,-2.988945e+09,37.0,6.582661e+09,40.0,1
1171862,874039100,TSM,0.0,2022,2,2022,1,336062000,-478448000,35,106,2178450000,2320836000,20861374,19354126,-2.988945e+09,37.0,6.582661e+09,40.0,3
1171863,874039100,TSM,0.0,2022,3,2022,2,86046000,-727861000,32,102,1462058000,2103873000,17861293,20174241,-2.988945e+09,37.0,6.582661e+09,40.0,1
1171864,874039100,TSM,0.0,2022,4,2022,3,1754570000,-381843000,20,109,2816748000,1444021000,41083471,17643930,-2.988945e+09,37.0,6.582661e+09,40.0,1
1171908,874039100,TSM,1.0,2022,1,2021,4,34307000,-5733000,26,7,178000000,149426000,1479495,1324709,-1.454870e+08,7.0,3.901710e+08,8.0,0
1171909,874039100,TSM,1.0,2022,2,2022,1,22754000,-27592000,7,20,132326000,137164000,1268219,1140075,-1.454870e+08,7.0,3.901710e+08,8.0,0
1171910,874039100,TSM,1.0,2022,3,2022,2,51331000,-17739000,9,18,140020000,106428000,1695865,1019816,-1.454870e+08,7.0,3.901710e+08,8.0,0
1171911,874039100,TSM,1.0,2022,4,2022,3,3000,-59626000,1,24,73986000,133609000,1079105,1617433,-1.454870e+08,7.0,3.901710e+08,8.0,0

In [20]:
hedge_data_1 = hedge_data.groupby(
    ['CUSIP', 'TICKER', 'MANAGER_LEVEL', 'YEAR', 'QUARTER', 'DATA_YEAR', 'DATA_QURT']
).agg({
    'INC_VALUE': 'sum', 'DRC_VALUE': 'sum', 'INC_COUNT': 'sum', 'DRC_COUNT': 'sum', 'TOTAL_VALUE': 'sum',
    'TOTAL_PREVALUE': 'sum', 'TOTAL_SSHPRNAMT': 'sum', 'TOTAL_PRESSHPRNAMT': 'sum',  # 这里之前的数据是对基金的评估
    'HIS_AVG_DRC_VAL': 'sum', 'HIS_DRC_COUNT': 'sum',  # 该行及之后的数据是当前基金在当前ticker上的情况
    'HIS_AVG_INC_VAL': 'sum', 'HIS_INC_COUNT': 'sum',
}).reset_index()

In [23]:
hedge_data_1[(hedge_data_1['TICKER'] == 'TSM') & (hedge_data_1['YEAR'] == 2022) & (hedge_data_1['MANAGER_LEVEL'].isin([0, 1]))]

,CUSIP,TICKER,MANAGER_LEVEL,YEAR,QUARTER,DATA_YEAR,DATA_QURT,INC_VALUE,DRC_VALUE,INC_COUNT,DRC_COUNT,TOTAL_VALUE,TOTAL_PREVALUE,TOTAL_SSHPRNAMT,TOTAL_PRESSHPRNAMT,HIS_AVG_DRC_VAL,HIS_DRC_COUNT,HIS_AVG_INC_VAL,HIS_INC_COUNT
1171861,874039100,TSM,0.0,2022,1,2021,4,797678600,-81265000,126,22,2861789600,2145376000,20740967,19200403,-2.988945e+09,37.0,6.582661e+09,40.0
1171862,874039100,TSM,0.0,2022,2,2022,1,336062000,-478448000,35,106,2178450000,2320836000,20861374,19354126,-2.988945e+09,37.0,6.582661e+09,40.0
1171863,874039100,TSM,0.0,2022,3,2022,2,86046000,-727861000,32,102,1462058000,2103873000,17861293,20174241,-2.988945e+09,37.0,6.582661e+09,40.0
1171864,874039100,TSM,0.0,2022,4,2022,3,1754570000,-381843000,20,109,2816748000,1444021000,41083471,17643930,-2.988945e+09,37.0,6.582661e+09,40.0
1171908,874039100,TSM,1.0,2022,1,2021,4,34307000,-5733000,26,7,178000000,149426000,1479495,1324709,-1.454870e+08,7.0,3.901710e+08,8.0
1171909,874039100,TSM,1.0,2022,2,2022,1,22754000,-27592000,7,20,132326000,137164000,1268219,1140075,-1.454870e+08,7.0,3.901710e+08,8.0
1171910,874039100,TSM,1.0,2022,3,2022,2,51331000,-17739000,9,18,140020000,106428000,1695865,1019816,-1.454870e+08,7.0,3.901710e+08,8.0
1171911,874039100,TSM,1.0,2022,4,2022,3,3000,-59626000,1,24,73986000,133609000,1079105,1617433,-1.454870e+08,7.0,3.901710e+08,8.0